# Introducción a Numpy

In [ ]:
import numpy as np

# Arrays
    Es una estructura de datos
    un axis
    un shape (3,5)
    un size 15

In [19]:
#Array cuyos valores son todo 0
a = np.zeros((3,4))
print(a)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
print(a.ndim)
print(a.shape)
print(a.size)

2
(3, 4)
12


# Describe el array
    

In [17]:
#ejemplo 2
a= np.zeros((2,3,4))
print(a)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [18]:
print(a.ndim)
print(a.shape)
print(a.size)

3
(2, 3, 4)
24
